name: workflow Overview

on:
   workflow_dispatch:
   push:
     branches:
      - main
   
jobs:
  my_self_hosted_job:
   name: my self hosted job
   runs-on: self-hosted
   steps:
     - name: step in self-hosted runner 
       id: selfHOsted
       shell: sh
       run: 
        echo this is a mutiline comment
        echo and this job has been executed from my self-hosted runner 
  a_simple_job:
    name: my simple job name
    runs-on: ubuntu-latest
    steps:
      - name: name of my step
        id: stepId
        run: echo "this is sample step"
      - name: step with another shell
        id: shellStep
        shell: python
        run: print("THis is using python shell")
      
        
